/**
 *
 */
export class RouterPaths {
  //
  static readonly bundle_name = 'com.bye.ane.cloudmusic'
  //
  static readonly entry_module_name = 'entry'
  //
  static readonly index_ability_name = 'IndexAbility'
  //
}

//
export class RouterLaunchPaths {
  //
  static readonly welcome_page_path = 'feature/entry/ui/pages/welcome_page'
  //

}

//
export class RouterLoginPaths {
  //
  static readonly login_ability_name = 'LoginAbility'
  //

}

//
export class RouterIndexPaths {
  //
  static readonly index_ability_name = 'IndexAbility'

  //

  static readonly index_page_path = 'feature/index/ui/pages/index_page'
}

//
export class RouterHomePaths {
  //

  //
}